---

- hosts: all
  become: true
  tasks:

  - name: install updates (centos)
    package:
      update_only: yes
      update_cache: yes

- hosts: web_server
  become: true
  tasks:
  
  - name: install httpd package
    package:
        name:
           - httpd
           - php
        state: latest

- hosts: db_server
  become: true
  tasks:
    
    - name: install mariadb package
      package:
       name: mariadb
       state: latest

- hosts: all
  become: true
  tasks:

    - name: install samba package
      package:
       name: samba      
